<a href="https://colab.research.google.com/github/ZaremaDibirova/Pandas_practise/blob/main/Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
np.random.rand(10)

array([0.43884781, 0.13489656, 0.44703872, 0.95566665, 0.03237864,
       0.29026239, 0.75192976, 0.24255158, 0.07598131, 0.51613379])

In [13]:
np.random.randint(0,20,(6,5))

array([[ 8,  9, 14,  9,  5],
       [ 4, 18,  7, 16, 14],
       [ 6, 10,  0, 17,  0],
       [12, 19, 16, 18,  4],
       [19, 17,  0, 16, 19],
       [14, 19, 14, 11, 10]])

In [20]:
np.zeros((8,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.eye(5)*3

array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [24]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [26]:
np.logspace(1,2)

array([ 10.        ,  10.48113134,  10.98541142,  11.51395399,
        12.06792641,  12.64855217,  13.25711366,  13.89495494,
        14.56348478,  15.26417967,  15.9985872 ,  16.76832937,
        17.57510625,  18.42069969,  19.30697729,  20.23589648,
        21.20950888,  22.22996483,  23.29951811,  24.42053095,
        25.59547923,  26.82695795,  28.11768698,  29.47051703,
        30.88843596,  32.37457543,  33.93221772,  35.56480306,
        37.2759372 ,  39.06939937,  40.94915062,  42.9193426 ,
        44.98432669,  47.14866363,  49.41713361,  51.79474679,
        54.28675439,  56.89866029,  59.63623317,  62.50551925,
        65.51285569,  68.6648845 ,  71.9685673 ,  75.43120063,
        79.06043211,  82.86427729,  86.85113738,  91.0298178 ,
        95.40954763, 100.        ])

In [27]:
df=pd.read_csv('Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [30]:
df['TV and Radio']=df['TV']+df['radio']

In [31]:
df.head()

TV  radio  newspaper  sales  TV and Radio
0  230.1   37.8       69.2   22.1         267.9
1   44.5   39.3       45.1   10.4          83.8
2   17.2   45.9       69.3    9.3          63.1
3  151.5   41.3       58.5   18.5         192.8
4  180.8   10.8       58.4   12.9         191.6

In [32]:
df.drop('TV and Radio',axis=1,inplace=True)

In [33]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [34]:
df.set_index('sales',drop=True,inplace=True)

In [35]:
df.head()

TV  radio  newspaper
sales                         
22.1   230.1   37.8       69.2
10.4    44.5   39.3       45.1
9.3     17.2   45.9       69.3
18.5   151.5   41.3       58.5
12.9   180.8   10.8       58.4

In [36]:
df[df['radio']==10.8]

TV  radio  newspaper
sales                         
12.9   180.8   10.8       58.4
9.9     75.5   10.8        6.0

In [38]:
df.iloc[4:9]

TV  radio  newspaper
sales                         
12.9   180.8   10.8       58.4
7.2      8.7   48.9       75.0
11.8    57.5   32.8       23.5
13.2   120.2   19.6       11.6
4.8      8.6    2.1        1.0

In [42]:
df[(df['radio']==10.8) & (df['newspaper']==58.4)]

TV  radio  newspaper
sales                         
12.9   180.8   10.8       58.4

In [44]:
df.describe()

TV       radio   newspaper
count  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000
std     85.854236   14.846809   21.778621
min      0.700000    0.000000    0.300000
25%     74.375000    9.975000   12.750000
50%    149.750000   22.900000   25.750000
75%    218.825000   36.525000   45.100000
max    296.400000   49.600000  114.000000

In [46]:
df.describe().T

count      mean        std  min     25%     50%      75%    max
TV         200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
radio      200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
newspaper  200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0